// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpx8PmHcgvb0VJ9FrBYTjjz-4wgiUv50w',
    appId: '1:740496630039:web:902814523e90e779c81752',
    messagingSenderId: '740496630039',
    projectId: 'ceylontix-app',
    authDomain: 'ceylontix-app.firebaseapp.com',
    storageBucket: 'ceylontix-app.firebasestorage.app',
    measurementId: 'G-BLCCQXPY17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDibVdNym9Gs5r4XvDtB-HZCyG7Hk-gDp0',
    appId: '1:740496630039:android:1bf384d13cbd5564c81752',
    messagingSenderId: '740496630039',
    projectId: 'ceylontix-app',
    storageBucket: 'ceylontix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcmrSDEQuwLOaLEF-DlR3E2wYu1AJjLt8',
    appId: '1:740496630039:ios:e9adeb47428a433bc81752',
    messagingSenderId: '740496630039',
    projectId: 'ceylontix-app',
    storageBucket: 'ceylontix-app.firebasestorage.app',
    iosBundleId: 'com.example.ceylontixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcmrSDEQuwLOaLEF-DlR3E2wYu1AJjLt8',
    appId: '1:740496630039:ios:e9adeb47428a433bc81752',
    messagingSenderId: '740496630039',
    projectId: 'ceylontix-app',
    storageBucket: 'ceylontix-app.firebasestorage.app',
    iosBundleId: 'com.example.ceylontixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpx8PmHcgvb0VJ9FrBYTjjz-4wgiUv50w',
    appId: '1:740496630039:web:7415ad5f472c92e1c81752',
    messagingSenderId: '740496630039',
    projectId: 'ceylontix-app',
    authDomain: 'ceylontix-app.firebaseapp.com',
    storageBucket: 'ceylontix-app.firebasestorage.app',
    measurementId: 'G-EYVJENKGMT',
  );
}
