import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'src/presentation/screens/admin/admin_login_screen.dart';

void main() async {
  // Ensure that Flutter bindings are initialized before calling Firebase.
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const CeylonTixApp());
}

class CeylonTixApp extends StatelessWidget {
  const CeylonTixApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CeylonTix',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Let's define a primary color for a consistent theme
        primaryColor: const Color(0xFF0D47A1), // A deep, professional blue
        fontFamily: 'Poppins', // A modern, clean font
      ),
      // For now, we set the AdminLoginScreen as the home page to test it.
      home: const AdminLoginScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
